# Generated by Django 4.2.3 on 2023-07-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(default='NONE', upload_to='media'),
            preserve_default=False,
        ),
    ]
